# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollcharge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tollcharge',
            name='location',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus'), ('Auto', 'Auto')], max_length=300),
        ),
    ]
