# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171020_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus'), ('Auto', 'Auto')], max_length=300)),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
